### ISSUE TITLE
Openapi `examples` property is not handled

### ISSUE THREAD

**Issue by g0di** [spec-first/connexion#1005]
Hello there,

### Description

After trying to use the `examples` property on my openapi specification, it ended up by an `InvalidSpecification` exception at app start.

### Expected behaviour

`examples` property can be used within the openapi specification and is correctly handled (displayed in swagger-ui console)

### Actual behaviour

When `examples` property is used in the specification the following exception is raised at app startup.

```
Traceback (most recent call last):
  File "/Users/gody/.pyenv/versions/3.5.6/lib/python3.5/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/Users/gody/.pyenv/versions/3.5.6/lib/python3.5/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/Users/gody/.pyenv/versions/3.5.6/lib/python3.5/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/gody/.pyenv/versions/3.5.6/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/gody/.pyenv/versions/3.5.6/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/gody/.pyenv/versions/3.5.6/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/gody/.pyenv/versions/3.5.6/lib/python3.5/site-packages/gunicorn/util.py", line 368, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/Users/gody/dev/earthlab/workspace/storage-api/storage_api/__init__.py", line 23, in create_app
    strict_validation=True,
  File "/Users/gody/dev/earthlab/workspace/storage-api/pip_modules/connexion/apps/flask_app.py", line 54, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/Users/gody/dev/earthlab/workspace/storage-api/pip_modules/connexion/apps/abstract.py", line 155, in add_api
    options=api_options.as_dict())
  File "/Users/gody/dev/earthlab/workspace/storage-api/pip_modules/connexion/apis/abstract.py", line 73, in __init__
    self.specification = Specification.load(specification, arguments=arguments)
  File "/Users/gody/dev/earthlab/workspace/storage-api/pip_modules/connexion/spec.py", line 151, in load
    return cls.from_file(spec, arguments=arguments)
  File "/Users/gody/dev/earthlab/workspace/storage-api/pip_modules/connexion/spec.py", line 108, in from_file
    return cls.from_dict(spec)
  File "/Users/gody/dev/earthlab/workspace/storage-api/pip_modules/connexion/spec.py", line 146, in from_dict
    return OpenAPISpecification(spec)
  File "/Users/gody/dev/earthlab/workspace/storage-api/pip_modules/connexion/spec.py", line 39, in __init__
    self._validate_spec(raw_spec)
  File "/Users/gody/dev/earthlab/workspace/storage-api/pip_modules/connexion/spec.py", line 232, in _validate_spec
    raise InvalidSpecification.create_from(e)
connexion.exceptions.InvalidSpecification: {'description': 'The request could not complete', 'content': {'application/json': {'schema': {'$ref': '#/components/schemas/Problem', 'x-scope': ['']}}}} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['components']['properties']['responses']['additionalProperties']:
    {'oneOf': [{'$ref': '#/definitions/response'},
               {'$ref': '#/definitions/reference'}]}

On instance['components']['responses']['Problem']:
    {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/Problem',
                                                 'x-scope': ['']}}},
     'description': 'The request could not complete'}
```

### Steps to reproduce

Simply use the `examples` property in your specification (see https://swagger.io/docs/specification/adding-examples/) then start your application

### Additional info:

Output of the commands:

- `python --version`
3.5.6
- `pip show connexion | grep "^Version\:"`
2.3.0

Thank you ;)

**Comment by jasonrhaas** [comment]
I'm also seeing this issue.  If the maintainers verify it as a bug I can potentially work on a fix.

**Comment by RobbeSneyders** [comment]
Cannot reproduce. Please reopen with a minimal working example if you encounter this issue again.
