### ISSUE TITLE
No support for `anyOf` in `parameters`

### ISSUE THREAD

**Issue by FFY00** [spec-first/connexion#1013]
### Description
Currently, we are unable to use `anyOf` in the `schema` of parameters.

### Actual behaviour
```
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/.local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/root/.local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 141, in wrapper
    request.path_params = self.resolve_path(path_params)
  File "/usr/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 183, in resolve_path
    return self.resolve_params(path_data, 'path')
  File "/usr/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 110, in resolve_params
    if (param_schema is not None and param_schema['type'] == 'array'):
```

### Steps to reproduce
Use this specification: https://gist.github.com/FFY00/878f59ec427ef05867cc4f57ba0f17a5

### Additional info:

Output of the commands:

- `python --version`
```
Python 3.7.4
```
- `pip show connexion | grep "^Version\:"`
```
Version: 2.3.0
```

**Comment by crunk1** [comment]
Got the same issue, except with `oneOf`.

**Comment by tomghyselinck** [comment]
> 
> We should rename the issue to specifically call out that this is happening with parameters `in: path`

Hi, we have the same issue with `in: query`. So it is not limited to `in: path` IMHO.

**Comment by RobbeSneyders** [comment]
Closing in favor of #1569.
