### ISSUE TITLE
Connexion not supporting OpenApi 3.0 compliant array definition 

### ISSUE THREAD

**Issue by jebeckford** [spec-first/connexion#1231]
### Description
**2 related issues:**

1.  An array definition that does not define data type (supports arbitrary data types) is an OpenApi 3.0 supported and valid definition.  However, the Connexion parameter validator is not supporting it.  Example:

        - in: query
          name: X
          schema:
            type: array
            items: {}

2. An array definition that lists multiple supported data types using a oneOf tag is an OpenApi 3.0 supported and valid definition.  However, the Connexion parameter validator is not supporting it.  Example:

        - in: query
          name: X
          schema:
          type: array
          items:
            oneOf:
                - type: string
                - type: integer

For reference where I am getting the OpenApi 3.0 supported syntax:
https://swagger.io/docs/specification/data-models/data-types/

### Expected behaviour
I'm running Connexion 2.6 and my understanding is it has supported OpenApi 3.0 since version 2.0 (https://opensource.zalando.com/blog/2018/11/connexion-20-release/).

So my expectation was that all valid OpenApi 3.0 array definitions would be supported but that is not the case.  I found that only arrays of single data type are supported.

### Actual behaviour

**ArrayOfNumber:**

```
curl -X GET "http://127.0.0.1:8080/cloudmesh/LogisticRegression/fit?X=5.3%2C%203.5%2C%201.4%2C%200.2%2C%205.9%2C%203.0%2C%205.1%2C%201.8&y=0%2C2&sample_weight=1%2C1&X_shape_x=2&X_shape_y=4" -H "accept: text/plain"

127.0.0.1 - - [30/Apr/2020 21:08:57] "[37mGET /cloudmesh/LogisticRegression/fit?X=5.3%2C%203.5%2C%201.4%2C%200.2%2C%205.9%2C%203.0%2C%205.1%2C%201.8&y=0%2C2&sample_weight=1%2C1&X_shape_x=2&X_shape_y=4 HTTP/1.1[0m" 200 -
```

**ArrayOfAny:**

```
curl -X GET "http://127.0.0.1:8080/cloudmesh/LogisticRegression/fit?X=5.2%2C%203.5%2C%201.4%2C%200.2%2C%205.9%2C%203.0%2C%205.1%2C%201.8&y=0%2C2&sample_weight=1%2C1&X_shape_x=2&X_shape_y=4" -H "accept: text/plain"

[2020-04-30 21:04:00,294] ERROR in app: Exception on /cloudmesh/LogisticRegression/fit [GET]
Traceback (most recent call last):
  File "c:\users\jonathan\venv\env3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jonathan\venv\env3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jonathan\venv\env3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jonathan\venv\env3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jonathan\venv\env3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jonathan\venv\env3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jonathan\venv\env3\lib\site-packages\connexion\decorators\decorator.py", line 48, in wrapper
    response = function(request)
  File "c:\users\jonathan\venv\env3\lib\site-packages\connexion\decorators\uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "c:\users\jonathan\venv\env3\lib\site-packages\connexion\decorators\validation.py", line 360, in wrapper
    error = self.validate_query_parameter(param, request)
  File "c:\users\jonathan\venv\env3\lib\site-packages\connexion\decorators\validation.py", line 320, in validate_query_parameter
    return self.validate_parameter('query', val, param)
  File "c:\users\jonathan\venv\env3\lib\site-packages\connexion\decorators\validation.py", line 257, in validate_parameter
    converted_value = coerce_type(param, value, parameter_type, param_name)
  File "c:\users\jonathan\venv\env3\lib\site-packages\connexion\decorators\validation.py", line 65, in coerce_type
    converted = make_type(v, param_schema["items"]["type"])
KeyError: 'type'
127.0.0.1 - - [30/Apr/2020 21:04:00] "[35m[1mGET /cloudmesh/LogisticRegression/fit?X=5.2%2C%203.5%2C%201.4%2C%200.2%2C%205.9%2C%203.0%2C%205.1%2C%201.8&y=0%2C2&sample_weight=1%2C1&X_shape_x=2&X_shape_y=4 HTTP/1.1[0m" 500 -
```

**ArrayOfOneInList:**

```
curl -X GET "http://127.0.0.1:8080/cloudmesh/LogisticRegression/fit?X=5.1%2C%203.5%2C%201.4%2C%200.2%2C%205.9%2C%203.0%2C%205.1%2C%201.8&y=0%2C2&sample_weight=1%2C1&X_shape_x=2&X_shape_y=4" -H "accept: text/plain"

[2020-04-30 20:59:09,923] ERROR in app: Exception on /cloudmesh/LogisticRegression/fit [GET]
Traceback (most recent call last):
  File "c:\users\jonathan\venv\env3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jonathan\venv\env3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jonathan\venv\env3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jonathan\venv\env3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jonathan\venv\env3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jonathan\venv\env3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jonathan\venv\env3\lib\site-packages\connexion\decorators\decorator.py", line 48, in wrapper
    response = function(request)
  File "c:\users\jonathan\venv\env3\lib\site-packages\connexion\decorators\uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "c:\users\jonathan\venv\env3\lib\site-packages\connexion\decorators\validation.py", line 360, in wrapper
    error = self.validate_query_parameter(param, request)
  File "c:\users\jonathan\venv\env3\lib\site-packages\connexion\decorators\validation.py", line 320, in validate_query_parameter
    return self.validate_parameter('query', val, param)
  File "c:\users\jonathan\venv\env3\lib\site-packages\connexion\decorators\validation.py", line 257, in validate_parameter
    converted_value = coerce_type(param, value, parameter_type, param_name)
  File "c:\users\jonathan\venv\env3\lib\site-packages\connexion\decorators\validation.py", line 65, in coerce_type
    converted = make_type(v, param_schema["items"]["type"])
KeyError: 'type'
127.0.0.1 - - [30/Apr/2020 20:59:09] "[35m[1mGET /cloudmesh/LogisticRegression/fit?X=5.1%2C%203.5%2C%201.4%2C%200.2%2C%205.9%2C%203.0%2C%205.1%2C%201.8&y=0%2C2&sample_weight=1%2C1&X_shape_x=2&X_shape_y=4 HTTP/1.1[0m" 500 -
```

### Steps to reproduce

https://github.com/jebeckford/openapi_array_issue

### Additional info:

Output of the commands:

- `python --version`
Python 3.8.1

- `pip show connexion | grep "^Version\:"`
Version: 2.6.0

**Comment by matthijsramlab** [comment]
I am having the same problem..

**Comment by RobbeSneyders** [comment]
Closing in favor of #1569.
