### ISSUE TITLE
Bug in URI parser

### ISSUE THREAD

**Issue by HansBouwmeester** [spec-first/connexion#1235]
### Description

I believe this is a Connexion issue. When I (by mistake) specified a query parameter as `string[]=string` the URI parser fails with a TypeError:

```
[2020-05-08 16:42:01 -0700] [21510] [ERROR] Error handling request /v1/devices?expand[]=id
Traceback (most recent call last):
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/connexion/apps/abstract.py", line 249, in __call__
    return self.app(environ, start_response)
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/connexion/decorators/security.py", line 327, in wrapper
    return function(request)
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 141, in wrapper
    request.query = self.resolve_query(query)
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 215, in resolve_query
    return self.resolve_params(query_data, 'query')
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 113, in resolve_params
    values = self._resolve_param_duplicates(values, param_defn, _in)
  File "/Users/hansb/workspace/afterburner/.venv/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 235, in _resolve_param_duplicates
    return delimiter.join(values)
TypeError: sequence item 0: expected str instance, dict found
```
### Expected behavior
A "proper" 400 - Bad Request Error.

### Actual behaviour
See above.

### Steps to reproduce
See above.

### Additional info:

Output of the commands:

- `python --version`
Python 3.7.5
- `pip show connexion | grep "^Version\:"`
Version: 2.7.0

**Comment by RobbeSneyders** [comment]
Cannot reproduce. Feel free to reopen with a minimal reproducible example.
