### ISSUE TITLE
gunicorn workers fails to boot on connexion app with aiohttp backend

### ISSUE THREAD

**Issue by baskaran284** [spec-first/connexion#1547]
### Description
gevent, aiohttp.GunicornWebWorker or aiohttp.worker.GunicornUVLoopWebWorker fails to boot with connexion app object.

### Expected behaviour
[2022-06-02 01:40:35 +0530] [20917] [INFO] Starting gunicorn 20.1.0
[2022-06-02 01:40:35 +0530] [20917] [INFO] Listening at: https://0.0.0.0:8080 (20917)
[2022-06-02 01:40:35 +0530] [20917] [INFO] Using worker: aiohttp.GunicornWebWorker
[2022-06-02 01:40:35 +0530] [20918] [INFO] Booting worker with pid: 20918

### Actual behaviour

1. aiohttp.worker.GunicornUVLoopWebWorker

Traceback (most recent call last):
  File "/Users/virtualEnv/controller/lib/python3.10/site-packages/aiohttp/worker.py", line 57, in run
    self.loop.run_until_complete(self._task)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/Users/virtualEnv/controller/lib/python3.10/site-packages/aiohttp/worker.py", line 77, in _run
    raise RuntimeError(
RuntimeError: wsgi app should be either Application or async function returning Application, got <connexion.apps.aiohttp_app.AioHttpApp object at 0x106d258a0>

2. aiohttp.GunicornWebWorker

[2022-06-02 01:53:34 +0530] [21390] [ERROR] Exception in gunicorn worker
Traceback (most recent call last):
  File "/Users/virtualEnv/controller/lib/python3.10/site-packages/aiohttp/worker.py", line 57, in run
    self.loop.run_until_complete(self._task)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/virtualEnv/controller/lib/python3.10/site-packages/aiohttp/worker.py", line 77, in _run
    raise RuntimeError(
RuntimeError: wsgi app should be either Application or async function returning Application, got <connexion.apps.aiohttp_app.AioHttpApp object at 0x105e806a0>

3. gevent(fails on request)

Traceback (most recent call last):
  File "/Users/virtualEnv/controller/lib/python3.10/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/Users/virtualEnv/controller/lib/python3.10/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/Users/virtualEnv/controller/lib/python3.10/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/virtualEnv/controller/lib/python3.10/site-packages/connexion/apps/abstract.py", line 254, in __call__
    return self.app(environ, start_response)
TypeError: Application.__call__() takes 1 positional argument but 3 were given

### Steps to reproduce

#main.py

import connexion
app = connexion.AioHttpApp(__name__, specification_dir='./swagger/', options=options)

#command
gunicorn --bind 0.0.0.0:8080 --worker-class aiohttp.worker.GunicornWebWorker main:app

### Additional info:
Also tried different workers

Output of the commands:

- `python --version`
Python 3.10.2
- `pip show connexion | grep "^Version\:"` 
Version: 2.13.1

**Comment by BhaskarChezhiyan** [comment]
Hi @RobbeSneyders,

Thanks for the reply, accessing `app` object under `connexion.AioHttpApp` brings the server up. But none of the APIs are added. 

It returns 404 for all requests.
