### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by dangokuson** [spec-first/connexion#1577]
### Description
I faced this error when I try to debug on PyCharm
```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/sondn/workspace/projects/swagger-codegen/samples/server/petstore/flaskConnexion/swagger_server/__main__.py", line 16, in <module>
    main()
  File "/Users/sondn/workspace/projects/swagger-codegen/samples/server/petstore/flaskConnexion/swagger_server/__main__.py", line 9, in main
    app = connexion.App(__name__, specification_dir='./swagger/', debug=True)
  File "/Users/sondn/.virtualenvs/bstore/lib/python3.7/site-packages/connexion/apps/flask_app.py", line 31, in __init__
    super().__init__(import_name, FlaskApi, server=server, **kwargs)
  File "/Users/sondn/.virtualenvs/bstore/lib/python3.7/site-packages/connexion/apps/abstract.py", line 57, in __init__
    self.app = self.create_app()
  File "/Users/sondn/.virtualenvs/bstore/lib/python3.7/site-packages/connexion/apps/flask_app.py", line 35, in create_app
    app = flask.Flask(self.import_name, **self.server_args)
  File "/Users/sondn/.virtualenvs/bstore/lib/python3.7/site-packages/flask/app.py", line 575, in __init__
    instance_path = self.auto_find_instance_path()
  File "/Users/sondn/.virtualenvs/bstore/lib/python3.7/site-packages/flask/app.py", line 854, in auto_find_instance_path
    prefix, package_path = find_package(self.import_name)
  File "/Users/sondn/.virtualenvs/bstore/lib/python3.7/site-packages/flask/scaffold.py", line 873, in find_package
    package_path = _find_package_path(import_name)
  File "/Users/sondn/.virtualenvs/bstore/lib/python3.7/site-packages/flask/scaffold.py", line 824, in _find_package_path
    search_locations = iter(root_spec.submodule_search_locations)
TypeError: 'NoneType' object is not iterable
```
![image](https://user-images.githubusercontent.com/86276600/186558702-3f26ca59-ae34-4ed2-9652-d3e47a217dba.png)

Does anybody tell me how to debug on PyCharm?

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

```
connexion==2.14.1
python_dateutil ==2.8.2
setuptools >= 21.0.0
```

**Comment by RobbeSneyders** [comment]
This issue does not seem Connexion specific, and there's not enough info to help debug.
