### ISSUE TITLE
AttributeError: partially initialized module 'people' has no attribute 'read_all' (most likely due to a circular import)

### ISSUE THREAD

**Issue by HolimaX** [spec-first/connexion#1606]
### Description

During migration of ```swagger: 2.0``` to ```openapi: 3.0.x```, I was improving some swagger config. After finishing, I attempted to run my app, but it does not compiule and run anymore.

When calling add_api, the python throws error.

### Expected behaviour

Python compiles and runs app successfully.

### Actual behaviour

The following stacktrace is thrown:

Traceback (most recent call last):
  File "/home/linards/Dokumenti/Dev/libgopyu/app.py", line 46, in <module>
    app.add_api(path, options = options)
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/apps/flask_app.py", line 72, in add_api
    api = super().add_api(specification, **kwargs)
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/apps/abstract.py", line 149, in add_api
    api = self.api_cls(specification,
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/apis/abstract.py", line 119, in __init__
    self.add_paths()
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/apis/abstract.py", line 229, in add_paths
    self._handle_add_operation_error(path, method, err.exc_info)
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/apis/abstract.py", line 244, in _handle_add_operation_error
    raise value.with_traceback(traceback)
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/resolver.py", line 68, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/utils.py", line 116, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/linards/Dokumenti/Dev/libgopyu/people.py", line 13, in <module>
    from app import __version__, __status__
  File "/home/linards/Dokumenti/Dev/libgopyu/app.py", line 46, in <module>
    app.add_api(path, options = options)
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/apps/flask_app.py", line 72, in add_api
    api = super().add_api(specification, **kwargs)
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/apps/abstract.py", line 149, in add_api
    api = self.api_cls(specification,
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/apis/abstract.py", line 119, in __init__
    self.add_paths()
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/apis/abstract.py", line 229, in add_paths
    self._handle_add_operation_error(path, method, err.exc_info)
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/apis/abstract.py", line 244, in _handle_add_operation_error
    raise value.with_traceback(traceback)
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/resolver.py", line 68, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/utils.py", line 125, in get_function_from_name
    function = deep_getattr(module, attr_path)
  File "/home/linards/.local/lib/python3.10/site-packages/connexion/utils.py", line 73, in deep_getattr
    return functools.reduce(getattr, attrs, obj)
AttributeError: partially initialized module 'people' has no attribute 'read_all' (most likely due to a circular import)

### Steps to reproduce

Create following app:

```
# app.py

# Create the application instance
options = {"serve_spec": True}
app = connexion.FlaskApp(__name__.split('.')[0], specification_dir='./', options = options)
CORS(app.app)
WSGIRequestHandler.protocol_version = "HTTP/1.1"

# Read the swagger.yml file to configure the endpoints
path = Path('swagger.yml')
if (path.is_file() & options['serve_spec'] is True):
    app.add_api(path, options = options)

# Enable Flask on Connexion
app = app.app

# Create a URL route in our application for "/"
@app.route('/',methods=['GET','POST','PUT','DELETE'])
```

```
# people.py

VERSION = {
    "Default": {
        "cod": 200,
        "version": __version__,
        "filter": "*",
        "flavor": "final"
    },
    "Current": {
        "cod": 200,
        "version": __version__,
        "filter": "*", 
        "flavor": __status__
    },
    "Latest": {
        "cod": 200,
        "version": __version__,
        "filter": "*",
        "flavor": "alpha"
    }
}

def read_ver():
    """
    This function responds to a request for /api/version
    with the complete lists of versions and their changelogs
    :return:        json string of list of version
    """
    # Create the list of versions from our data
    return [VERSION[key] for key in sorted(VERSION.keys())]
```

```
# swagger.yml

openapi: "3.0.3"
info:
  description: |
    <obfusciated>
  version: "<obfusciated>"
  title: <obfusciated>
  termsOfService: <obfusciated>
  contact:
    name: <obfusciated>
    url: <obfusciated>
    email: <obfusciated>
  license:
    name: MIT
    url: <obfusciated>

#basePath: /api
servers:
  - url: <obfusciated>
    description: Main (production) server

# Paths supported by the server application
paths:
  /version:
    get:
      operationId: people.read_ver
      tags:
        - version
      summary: Read the entire list of versions
      description: Read the list of versions
      parameters:
        - name: version
          in: query
          schema:
            type: string
          description: Name of version to get from version list
          required: true
        - name: filter
          in: query
          schema:
            type: string
            enum:
              - Latest
              - Current
              - Default
            default: Latest
          description: Filter for version presets
          required: false
      responses:
        200:
          description: Successfully read version list operation
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    cod:
                      type: string
                    version:
                      type: string
                    filter:
                      type: string
                    flavor:
                      type: string
```

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

Python 3.10.7
Version: 2.14.1

**Comment by HolimaX** [comment]
app.py:

```from flask import render_template
from flask import config
from flask_cors import CORS

from werkzeug.serving import WSGIRequestHandler

import connexion
import logging

from datetime import date```

people.py:

```
# System modules
from datetime import datetime

# 3rd party modules
from flask import make_response, abort

from app import __version__, __status__```

**Comment by HolimaX** [comment]
> Hi @HolimaX, Since the issue is related to a circular import, could you include your imports?

Pasted code snipps above ;)

**Comment by RobbeSneyders** [comment]
Connexion imports `people.py` when resolving the operation_id in your spec on calling `add_api()` in `app.py`.

So `from app import __version__, __status__` in `people.py` is causing the circular import.

You should be able to restructure your code to prevent this.
