### ISSUE TITLE
name and qual name appear to be missing from decorated flask operation

### ISSUE THREAD

**Issue by matthewdeanmartin** [spec-first/connexion#1666]
### Description

I think `\_\_name\_\_` and `\_\_qualname\_\_` missing from FlaskOperator

I think it needs this

```
class FlaskOperation:
    def __init__(
        self,
        fn: t.Callable,
        jsonifier: Jsonifier,
        operation_id: str,
        pythonic_params: bool,
    ) -> None:
        # Something is acting like a wrapper but not copying these
        self.__name__ = fn.__name__
        self.__qualname__ = fn.__qualname__
        # end of suggestion
        self._fn = fn
```

### Expected behaviour

decorated functions should have function/callable metadata like name and qualname

### Actual behaviour

Missing such metatadata.

### Steps to reproduce

Install flask-limiter, decorate a controller function, call it, boom.  See stack trace below.

### Additional info:

```
❯ python --version
Python 3.11.1
❯ pip show connexion | grep "^Version\:"
Version: 3.0.dev0
```

#### error message
```
2023-03-05 10:25:31,498 [ERROR] search_service.uwsgi_config: HTTP Error
Traceback (most recent call last):
  File "E:\.virtualenv\search_service-QBGhH39p\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.virtualenv\search_service-QBGhH39p\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.virtualenv\search_service-QBGhH39p\Lib\site-packages\connexion\apps\flask.py", line 66, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.virtualenv\search_service-QBGhH39p\Lib\site-packages\connexion\decorators\main.py", line 122, in wrapper
    return decorated_function(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.virtualenv\search_service-QBGhH39p\Lib\site-packages\connexion\decorators\response.py", line 160, in wrapper
    handler_response = function(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.virtualenv\search_service-QBGhH39p\Lib\site-packages\connexion\decorators\parameter.py", line 84, in wrapper
    return function(**kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "E:\.virtualenv\search_service-QBGhH39p\Lib\site-packages\connexion\decorators\main.py", line 111, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.virtualenv\search_service-QBGhH39p\Lib\site-packages\flask_limiter\extension.py", line 1178, in __inner
    if view_func and not get_qualified_name(view_func) == name:
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.virtualenv\search_service-QBGhH39p\Lib\site-packages\flask_limiter\util.py", line 32, in get_qualified_name
    return f"{callable.__module__}.{callable.__name__}.{callable.__qualname__}"
                                    ^^^^^^^^^^^^^^^^^
AttributeError: 'FlaskOperation' object has no attribute '__name__'
```

**Comment by RobbeSneyders** [comment]
Thanks for the report @matthewdeanmartin 

Could you post a minimal reproducible example? I would like to check if we can refactor the `FlaskOperation` class to leverage `functools.wraps` instead of adding the attributes manually, and an example would be a big help.

**Comment by matthewdeanmartin** [comment]
Done: https://github.com/matthewdeanmartin/connexion_experiment

**Comment by RobbeSneyders** [comment]
Thanks! I submitted a PR.

I tested your example, and the error is now gone. It now raises another error instead, but I don't think this one is connexion related.

**Comment by RobbeSneyders** [comment]
3.0.0a2 has been released containing this fix.
