### ISSUE TITLE
FlaskApp fails to load API with no explicit server url or base path

### ISSUE THREAD

**Issue by maxiberta** [spec-first/connexion#1724]
### Description
Adding an API to a FlaskApp app with no `servers` section in the spec and no `base_path` argument to `.add_api()` produces a `ValueError: 'name' may not be empty.` error while adding the Flask blueprint.

For example, run the "jwt" app at `examples/jwt/app.py` and hit the API at `/auth/123`. 
(Note this has nothing to do with JWT itself; the issue can be easily reproduced with any app that loads an API spec with the conditions above. The jwt example happens to fit exactly for this issue; as most other examples load specs under `/openapi` and `/swagger`.)

### Expected behaviour
The app should bootstrap successfully, and the endpoint should return a JWT token string for authentication.

### Actual behaviour
Client gets `Internal Server Error` and the server throws an exception.

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/max/src/connexion/examples/jwt/env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/max/src/connexion/examples/jwt/env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/max/src/connexion/connexion/apps/abstract.py", line 272, in __call__
    return await self.middleware(scope, receive, send)
  File "/home/max/src/connexion/connexion/middleware/main.py", line 467, in __call__
    self.app, self.middleware_stack = self._build_middleware_stack()
  File "/home/max/src/connexion/connexion/middleware/main.py", line 317, in _build_middleware_stack
    app.add_api(
  File "/home/max/src/connexion/connexion/apps/flask.py", line 158, in add_api
    api = FlaskApi(specification, **kwargs)
  File "/home/max/src/connexion/connexion/apps/flask.py", line 74, in __init__
    super().__init__(*args, **kwargs)
  File "/home/max/src/connexion/connexion/middleware/abstract.py", line 80, in __init__
    super().__init__(*args, **kwargs)
  File "/home/max/src/connexion/connexion/middleware/abstract.py", line 53, in __init__
    self._set_base_path(base_path)
  File "/home/max/src/connexion/connexion/apps/flask.py", line 78, in _set_base_path
    self._set_blueprint()
  File "/home/max/src/connexion/connexion/apps/flask.py", line 82, in _set_blueprint
    self.blueprint = flask.Blueprint(
  File "/home/max/src/connexion/examples/jwt/env/lib/python3.10/site-packages/flask/blueprints.py", line 196, in __init__
    raise ValueError("'name' may not be empty.")
ValueError: 'name' may not be empty.
INFO:     127.0.0.1:58518 - "GET /auth/123 HTTP/1.1" 500 Internal Server Error

```

### Steps to reproduce
Clone `connexion` and set up a virtual env to run the example jwt app:
```sh
$ cd examples/jwt
$ python -m venv env
$ env/bin/pip install -e '../..[flask]' 'python-jose[cryptography]' uvicorn
$ env/bin/python app.py
...
INFO:     Application startup complete.
```
Hit the service:
```sh
$ curl localhost:8080/auth/123
Internal Server Error
```

### Additional info:
It all works if we add `servers` to the spec with a url that is different to `/`, e.g. `/test`:

```diff
diff --git a/examples/jwt/spec/openapi.yaml b/examples/jwt/spec/openapi.yaml
index 71af5cc..bbcbbd6 100644
--- a/examples/jwt/spec/openapi.yaml
+++ b/examples/jwt/spec/openapi.yaml
@@ -2,6 +2,8 @@ openapi: 3.0.0
 info:
   title: JWT Example
   version: '1.0'
+servers:
+  - url: /test
 paths:
   /auth/{user_id}:
     get:
```
```sh
$ curl localhost:8080/test/auth/123
some.random.looking.string...
```

But `- url: /` still fails.

Alternatively, we can call `app.add_api()` with a `base_path`, e.g.:
```diff
diff --git a/examples/jwt/app.py b/examples/jwt/app.py
index fdcbc90..172f718 100755
--- a/examples/jwt/app.py
+++ b/examples/jwt/app.py
@@ -47,7 +47,7 @@ def _current_timestamp() -> int:
 
 
 app = connexion.FlaskApp(__name__, specification_dir="spec")
-app.add_api("openapi.yaml")
+app.add_api("openapi.yaml", base_path="/test")
 
 
 if __name__ == "__main__":
```

And it works again.

But passing `/` as base path as in `app.add_api("openapi.yaml", base_path="/")` fails differently:
```
[2023-08-14 20:09:56,360] ERROR in app: Exception on /auth/123 [GET]
Traceback (most recent call last):
  File "/home/max/src/connexion/examples/jwt/env/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/max/src/connexion/examples/jwt/env/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/max/src/connexion/examples/jwt/env/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/max/src/connexion/examples/jwt/env/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/max/src/connexion/connexion/apps/flask.py", line 66, in __call__
    return self.fn(*args, **kwargs)
  File "/home/max/src/connexion/connexion/decorators/main.py", line 129, in wrapper
    request = self.framework.get_request(uri_parser=self.uri_parser)
  File "/home/max/src/connexion/connexion/decorators/main.py", line 71, in uri_parser
    uri_parser_class = self.uri_parser_class or operation.uri_parser_class
  File "/home/max/src/connexion/examples/jwt/env/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/home/max/src/connexion/examples/jwt/env/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of operation context. Make sure your app is wrapped in a ContextMiddleware and you're processing a request while accessing the context.
INFO:     127.0.0.1:37058 - "GET /auth/123 HTTP/1.1" 500 Internal Server Error
```

Output of the commands:

- `env/bin/python --version`
  - `Python 3.10.12`
- `pip show connexion | grep "^Version\:"`
  - `Version: 3.0.dev0`

**Comment by maxiberta** [comment]
The flask blueprint issue looks related to https://github.com/spec-first/connexion/issues/1542.

**Comment by maxiberta** [comment]
Sorry, not sure if the `Working outside of operation context` error is a separate issue.

Thanks!

**Comment by rishiraj88** [comment]
Thanks for the detailed listing. It's quite comprehensive.

**Comment by RobbeSneyders** [comment]
Thanks for the detailed issue @maxiberta! However I can't reproduce, running the JWT example works out of the box for me.

Which version of Flask do you have installed?

**Comment by RobbeSneyders** [comment]
I can indeed reproduce by installing Flask>=3. Relevant Flask issue: https://github.com/pallets/flask/issues/5010

**Comment by maxiberta** [comment]
> Which version of Flask do you have installed?

I can reproduce the issue with both Flask 2.3.3 and Flask 3.0.0. The non-empty blueprint requirement linked above seems to have been introduced in 2.3.0.
Thanks!
