### ISSUE TITLE
Use of batch create_or_update raises Exception

### ISSUE THREAD

**Issue by mdurieux** [spec-first/connexion#1731]
### Description

Use of batch create_or_update for a bunch of StructuredNode Objects

### Expected behaviour

Neo4j populated

### Actual behaviour
**Exception occurs:**
Traceback (most recent call last):
  File "/Users/i23704/git-python/neo4j-lab01/src/bnpparibasfortis/PopulateNeo4jFromHeliosDevGithub.py", line 49, in <module>
    Person.create_or_update(listPersons)
  File "/opt/homebrew/lib/python3.11/site-packages/neomodel/core.py", line 509, in create_or_update
    for specified, deflated in [
                               ^
  File "/opt/homebrew/lib/python3.11/site-packages/neomodel/core.py", line 510, in <listcomp>
    (p, cls.deflate(p, skip_empty=True)) for p in props
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/neomodel/properties.py", line 92, in deflate
    if properties.get(name) is not None:
       ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

### Steps to reproduce

**Datamodel :** 

from neomodel import StructuredNode, StringProperty, RelationshipTo, RelationshipFrom, StructuredRel, DateProperty

class Dog(StructuredNode):
    name = StringProperty(required=True)
    owner = RelationshipTo('Person', 'owner')

class Person(StructuredNode):
    name = StringProperty(unique_index=True)
    pets = RelationshipFrom('Dog', 'owner')

**Code :**

with db.transaction:
    
    ###### This code is working fine
    people = Person.create_or_update(
        {'name': 'Tim', 'age': 83},
        {'name': 'Bob', 'age': 23},
        {'name': 'Jill', 'age': 34},
    )
    ######
    
    ###### The code hereunder does raise Exception above

    listPersons = []
    listPersons.append(Person(name= 'Susan'))
    listPersons.append(Person(name='Bob'))
    Person.create_or_update(listPersons)

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by mdurieux** [comment]
Sorry I misplaced this issue
