### ISSUE TITLE
Can't get past the getting started

### ISSUE THREAD

**Issue by ajoga** [spec-first/connexion#1784]
### Description

I'm just trying this out and I'm I can't get [the getting started part of the doc](https://connexion.readthedocs.io/en/latest/quickstart.html#creating-your-application) running.

So far I've got only two files:

./run.py:

```
from connexion import AsyncApp

app = AsyncApp(__name__)


def so_something():
    return []


app.add_api("openapi-spec.yml")
app.run()
```

I used [this example spec ](https://github.com/spec-first/connexion/blob/bcf4c63b32835eddd624d6b936abfccad1646908/examples/helloworld/spec/openapi.yaml#L1) as openapi-spec.yml 

### Expected behaviour

The application runs

### Actual behaviour

When I run `$ uvicorn run:app`, I get this stack trace:

> $ uvicorn run:app
> `ConnexionMiddleware.run` is optimized for development. For production, run using a dedicated ASGI server.
> Traceback (most recent call last):
>   File "/home/zzzz/xxx/wwww/.venv/bin/uvicorn", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 416, in main
>     run(
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
>     server.run()
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
>     return asyncio.run(self.serve(sockets=sockets))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zzzz/.asdf/installs/python/3.11.6/lib/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/home/zzzz/.asdf/installs/python/3.11.6/lib/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
>     config.load()
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
>     self.loaded_app = import_from_string(self.app)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
>     module = importlib.import_module(module_str)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zzzz/.asdf/installs/python/3.11.6/lib/python3.11/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/home/zzzz/xxx/wwww/specs/aa/run.py", line 11, in <module>
>     app.run()
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/connexion/apps/abstract.py", line 281, in run
>     self.middleware.run(import_string, **kwargs)
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/connexion/middleware/main.py", line 475, in run
>     uvicorn.run(app, **kwargs)
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
>     server.run()
>   File "/home/zzzz/xxx/wwww/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
>     return asyncio.run(self.serve(sockets=sockets))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/zzzz/.asdf/installs/python/3.11.6/lib/python3.11/asyncio/runners.py", line 186, in run
>     raise RuntimeError(
> RuntimeError: asyncio.run() cannot be called from a running event loop
> sys:1: RuntimeWarning: coroutine 'Server.serve' was never awaited

### Steps to reproduce

I use python 3.11.6, I also tried in 3.11.5 with a fresh virtualenv & installing connexion[uvicorn] from scratch.

### Additional info:

Output of the commands:

- `python --version`: 3.11.6
- `pip show connexion | grep "^Version\:"` 3.0.0

**Comment by ajoga** [comment]
It is of course 5 minutes after submitting an issue that I realize that one should **either**:

* have `app.run()` in code and execute with `$ python run.py` ;
* not have `app.run()` in the code and run `$ uvicorn run:app`.
