### ISSUE TITLE
Any valid endpoint fails with connexion 3.0.2 

### ISSUE THREAD

**Issue by Elthas17** [spec-first/connexion#1808]
### Description
Exception raised on any valid endpoint when using connexion 3.0.1 , works fine with connexion  2.14.2 

1.1.ip.adress - - [16/Nov/2023 15:43:49] "GET /v1/ui/ HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "Path\venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\flask\app.py", line 841, in dispatch_request
    self.raise_routing_exception(req)
  File "Path\venv\Lib\site-packages\flask\app.py", line 450, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "Path\venv\Lib\site-packages\flask\ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Path\venv\Lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "Path\venv\Lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\flask\app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\flask\app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\flask\app.py", line 759, in handle_user_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\connexion\apps\flask.py", line 245, in _http_exception
    raise starlette.exceptions.HTTPException(exc.code, detail=exc.description)
starlette.exceptions.HTTPException: 404: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
10.132.77.86 - - [16/Nov/2023 15:43:50] "GET /favicon.ico HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "Path\venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\flask\app.py", line 841, in dispatch_request
    self.raise_routing_exception(req)
  File "Path\venv\Lib\site-packages\flask\app.py", line 450, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "Path\venv\Lib\site-packages\flask\ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Path\venv\Lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "Path\venv\Lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\flask\app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\flask\app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\flask\app.py", line 759, in handle_user_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\venv\Lib\site-packages\connexion\apps\flask.py", line 245, in _http_exception
    raise starlette.exceptions.HTTPException(exc.code, detail=exc.description)
starlette.exceptions.HTTPException: 404: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

### Expected behaviour

Any properly configured endpoined in the specification should work

### Actual behaviour

None work

### Steps to reproduce

- Please git pull the mimimal example i made for this issue on [connexion-issue repo](https://github.com/Elthas17/connexion-issue)
- use python 3.11.6 ,
- pip install requirements-failing.txt to have the endpoints return the execption above
- pip install requirements-working.txt to have it working again. 
- run wsgi.py to start the flask app

### Additional info:
Downgrading connexion to 2.14.2 resolves the issue

Output of the commands:

- `python --version`
 Python 3.11.6

- `pip show connexion | grep "^Version\:"`

Name: connexion
Version: 3.0.1
Summary: Connexion - API first applications with OpenAPI/Swagger
Home-page: https://github.com/spec-first/connexion
Author: Robbe Sneyders
Author-email: robbe.sneyders@gmail.com
License: Apache-2.0
Location: Path\venv\Lib\site-packages
Requires: asgiref, httpx, inflection, Jinja2, jsonschema, python-multipart, PyYAML, requests, starlette, typing-extensions, werkzeug
Required-by:

**Comment by asmip1999-boop** [comment]
Hi @RobbeSneyders 
I am facing this same error, my requirements.txt is as below:
supervisor
uwsgi
requests==2.32.4
urllib3==2.5.0
aws_requests_auth==0.4.3
connexion[flask]==3.0.6
flask==3.0.3
werkzeug==3.0.6

and my app.py
#!/usr/bin/env python3
"""SPS Bitdefender Connector Service """
import os
import connexion

FLASK_APP = connexion.FlaskApp(__name__, specification_dir='./swagger/')
FLASK_APP.add_api('swagger.yaml', arguments={
    'title': ('RESTful API for the SPS Bitdefender Connector Service.\n'
              'This API is used internally by development.\n')})


# wsgi app to expose
application = FLASK_APP.app

if __name__ == '__main__':
    # Port 8080 and debug mode when run standalone
    FLASK_APP.run(host=os.getenv("DEFAULT_HOST_IP"), debug=True, port=8080)

following the documentation when i switched to connexion 3.0.0, I changed my connexion.App to FlaskApp but I am still getting the same 404 error mentioned above, can you please help me with this, it's urgent
