### ISSUE TITLE
Can't handle requests with `connexion[flask]` without `uvicorn`.

### ISSUE THREAD

**Issue by rtb-zla-karma** [spec-first/connexion#1910]
### Description
I've recently updated Python to 3.12 and `connexion` and with other libs. It seems that in newer version it's impossible to run my server correctly without changing dependencies to `connexion[flask, uvicorn]`.

Previously I've had `connexion==2.14.0` and `flask==2.2.5` listed separately. In newer version when I run server it gives me this:
```python
[2024-04-15 09:21:16 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/app/application/api/api/app.py", line 17, in <module>
    app = connexion.FlaskApp(__name__, specification_dir="spec/")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/connexion/utils.py", line 284, in _delayed_error
    raise type(exc)(msg).with_traceback(exc.__traceback__)
  File "/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/connexion/__init__.py", line 19, in <module>
    from connexion.apps.flask import FlaskApi, FlaskApp
  File "/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/connexion/apps/flask.py", line 11, in <module>
    from a2wsgi import WSGIMiddleware
ModuleNotFoundError: Please install connexion using the 'flask' extra
```

So I've changed `connexion` to `connexion[flask]` and server was able to start but then I got "Internal Server Error" for any request sent. Server logs this:
```python
/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/jieba/__init__.py:44: SyntaxWarning: invalid escape sequence '\.'
  re_han_default = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&\._%\-]+)", re.U)
/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/jieba/__init__.py:46: SyntaxWarning: invalid escape sequence '\s'
  re_skip_default = re.compile("(\r\n|\s)", re.U)
/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/jieba/finalseg/__init__.py:78: SyntaxWarning: invalid escape sequence '\.'
  re_skip = re.compile("([a-zA-Z0-9]+(?:\.\d+)?%?)")
[2024-04-15 09:25:08 +0000] [9] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 282, in handle
    keepalive = self.handle_request(req, conn)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/proj-9TtSrW0h-py3.12/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AbstractApp.__call__() missing 1 required positional argument: 'send'
```

From what I've looked up installing `uvicorn` should solve the problem (according to guys in other project https://github.com/PaddleCV-SIG/PaddleLabel/issues/208#issuecomment-1805131259 ) . It did together with `-k uvicorn.workers.UvicornWorker` passed to `gunicorn` command.

### Expected/actual behaviour
`connexion[flask]` shouldn't practically require `uvicorn` to work. It also shouldn't pull async dependencies by default.

### Steps to reproduce

I will provide minimal steps and requirements which I think will help to reproduce the issue. If it doesn't work let me know and I will check what more I can provide.

#### Command

`gunicorn --config application/api/api/gunicorn_config.py application.api.api.app:app`

#### Files

```python
# application/api/api/gunicorn_config.py
# type: ignore

import os

bind = "0.0.0.0:8000"
reload = True
workers = 1
worker_connections = 100
threads = 4
timeout = 60
```

```python
# application/api/api/app.py
import asyncio

import connexion

class ThreadSharedEventLoopPolicy(asyncio.DefaultEventLoopPolicy):
    _loop = None

    def get_event_loop(self):
        if self._loop is None:
            self.set_event_loop(self.new_event_loop())
        return self._loop

    def set_event_loop(self, loop):
        self._loop = loop

# needed for asyncio working correctly with Flask
asyncio.set_event_loop_policy(ThreadSharedEventLoopPolicy())

app = connexion.FlaskApp(__name__, specification_dir="spec/")
app.add_api(
    specification="api.yaml",
    strict_validation=True,
    validate_responses=True,
)

if __name__ == "__main__":
    app.run(debug=True)
```

### Additional info:

Run and build through docker-compose and `poetry run`.

Output of the commands:

- `python --version`
  - `Python 3.12.2`
- `pip show connexion | grep "^Version\:"`
  - `Version: 3.0.6`

```
$ pip freeze
a2wsgi==1.10.4
anyio==4.3.0
asgiref==3.8.1
attrs==23.2.0
blinker==1.7.0
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
connexion==3.0.6
Flask==3.0.2
gunicorn==21.2.0
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
inflection==0.5.1
itsdangerous==2.1.2
Jinja2==3.1.3
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
MarkupSafe==2.1.5
packaging==24.0
python-multipart==0.0.9
PyYAML==6.0.1
referencing==0.34.0
requests==2.31.0
rpds-py==0.18.0
sniffio==1.3.1
starlette==0.37.2
typing_extensions==4.11.0
urllib3==2.2.1
Werkzeug==3.0.2
```

### Outro

If I've misconfigured something let me know. I will try to change it in my app and I will let you know the outcome.

**Comment by RobbeSneyders** [comment]
Hi @rtb-zla-karma, this is expected behavior for Connexion 3.

Please refer to the documentation on [how to migrate to Connexion 3](https://connexion.readthedocs.io/en/latest/v3.html), and on [how to run your application](https://connexion.readthedocs.io/en/latest/quickstart.html#running-your-application).
