### ISSUE TITLE
Stack trace not available to logger in v3 error handler function

### ISSUE THREAD

**Issue by chrisinmtown** [spec-first/connexion#2019]
### Description

Please help me convince the V3 error-handler function to log a complete stack trace when an exception is raised. As far as I can tell, the stack trace is not available, and that change is a regression from V2. A stack trace is critical for discovering what really failed. For example, if some function raises `KeyError('1')` the message is just `1` and that's not really helpful if operations brings that back from a production error! For what it's worth, I also tried calling `traceback.print_exc()` in my error-handler function, with no better result.

### Expected behaviour

In a function hooked via the `add_error_handler` function, calling `logger.exception` will log a full stack trace.

### Actual behaviour

In a function hooked via the `add_error_handler` function, calling `logger.exception` yields only a string version of the exception, same as calling `logger.error`; no stack trace is logged.

### Steps to reproduce

Start with the directory https://github.com/spec-first/connexion/tree/main/examples/helloworld and add the python files with the content below.

Here's `hello_v2.py` for Connexion *V2* which works as I expect, calling `logger.exception` prints a stack trace on exception:
```
from connexion import App
import logging


def handle_exception(ex):
    logger.exception("Request caused exc: %s", ex)
    return {"detail": str(ex)}, 500


def fall_on_face() -> None:
    logger.warning("Prepare to crash")
    raise ValueError("I would prefer not to")


def post_greeting(name: str) -> str:
    logger.info("name is %s", name)
    fall_on_face()


logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)
app = App(__name__, specification_dir="spec/")
app.add_error_handler(Exception, handle_exception)
app.add_api("openapi.yaml", arguments={"title": "Hello World Example"})
app.add_api("swagger.yaml", arguments={"title": "Hello World Example"})


if __name__ == "__main__":
    app.app.run(port=8080)
```

Here's `hello_v3.py` for Connexion *V3* which somehow does not preserve the stack trace (?)
```
from connexion import FlaskApp
from connexion.lifecycle import ConnexionRequest, ConnexionResponse
from connexion.problem import problem
import logging
from pathlib import Path


def handle_exception(
        request: ConnexionRequest,
        ex: Exception) -> ConnexionResponse:
    logger.exception("Request caused exc: %s", ex)
    return problem(title='Exception', status=500, detail=str(ex))


def fall_on_face() -> None:
    logger.warning("Prepare to crash")
    raise ValueError("I would prefer not to")


def post_greeting(name: str) -> str:
    logger.info("name is %s", name)
    fall_on_face()


logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)
app = FlaskApp(__name__, specification_dir="spec/")
app.add_error_handler(Exception, handle_exception)
app.add_api("openapi.yaml", arguments={"title": "Hello World Example"})
app.add_api("swagger.yaml", arguments={"title": "Hello World Example"})


if __name__ == "__main__":
    app.run(f"{Path(__file__).stem}:app", port=8080)
```

Next you'll have to create two virtual environments:
```
python3 -m venv venv-v2
source venv-v2/bin/activate
pip install 'connexion[flask,swagger-ui]<3'             
deactivate

python3 -m venv venv-v3
source venv-v3/bin/activate
pip install 'connexion[flask,swagger-ui]>=3.1.0'
deactivate
```

Now you can run the v2 version, which yields a stack trace:
1) activate the v2 venv: `source venv-v2/bin/activate`
2) create a symlink: `ln -s hello_v2.py hello.py` (the spec files point to module `hello`)
3) run the app: `python3 hello.py`
4) view the swagger UI, click try it out. 

Here's the log output I get from v2:
```
INFO:hello:name is dave
WARNING:hello:Prepare to crash
ERROR:__main__:Request caused exc: I would prefer not to
Traceback (most recent call last):
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v2/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v2/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v2/lib/python3.12/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v2/lib/python3.12/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v2/lib/python3.12/site-packages/connexion/decorators/validation.py", line 196, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v2/lib/python3.12/site-packages/connexion/decorators/validation.py", line 399, in wrapper
    return function(request)
           ^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v2/lib/python3.12/site-packages/connexion/decorators/produces.py", line 41, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v2/lib/python3.12/site-packages/connexion/decorators/parameter.py", line 120, in wrapper
    return function(**kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/hello.py", line 20, in post_greeting
    fall_on_face()
  File "/Users/me/git/github/connexion_spec_first/examples/exception/hello.py", line 15, in fall_on_face
    raise ValueError("I would prefer not to")
ValueError: I would prefer not to
INFO:werkzeug:127.0.0.1 - - [13/Dec/2024 13:24:50] "POST /openapi/greeting/dave HTTP/1.1" 500 -
```

Finally you can run the v3 version:
1) activate the v3 venv: `source venv-v3/bin/activate`
2) create a symlink: `ln -s hello_v3.py hello.py`  (again this avoids changing the operation ID in the spec files)
3) run the app: `python3 hello.py`
4) view the swagger UI, click try it out. 

Here's the log output I get from v3:
```
INFO:hello:name is dave
WARNING:hello:Prepare to crash
ERROR:hello:Request caused exc: I would prefer not to
NoneType: None
INFO:     127.0.0.1:58799 - "POST /openapi/greeting/dave HTTP/1.1" 500 Internal Server Error
```

I /think/ (but am not sure) that the line with `NoneType: None` shown after my ERROR log output and before the access-log entry might be Connexion trying to print a stack trace?

For what it's worth, if no error handler function is hooked, I get a full stack trace on the console! I'll show it here just for completeness. 
```
INFO:hello:name is dave
WARNING:hello:Prepare to crash
ERROR:connexion.middleware.exceptions:ValueError('I would prefer not to')
Traceback (most recent call last):
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/middleware/swagger_ui.py", line 222, in __call__
    await self.router(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/starlette/routing.py", line 460, in handle
    await self.app(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/starlette/routing.py", line 765, in app
    await self.default(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/middleware/swagger_ui.py", line 235, in default_fn
    await self.app(original_scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/middleware/routing.py", line 154, in __call__
    await self.router(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/me/routing.py", line 460, in handle
    await self.app(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/middleware/routing.py", line 48, in __call__
    await self.next_app(original_scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/middleware/abstract.py", line 264, in __call__
    return await operation(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/middleware/security.py", line 106, in __call__
    await self.next_app(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/middleware/abstract.py", line 264, in __call__
    return await operation(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/middleware/request_validation.py", line 142, in __call__
    await self.next_app(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/middleware/abstract.py", line 264, in __call__
    return await operation(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/middleware/lifespan.py", line 26, in __call__
    await self.next_app(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/middleware/abstract.py", line 264, in __call__
    return await operation(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/middleware/context.py", line 25, in __call__
    await self.next_app(scope, receive, send)
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/apps/flask.py", line 151, in __call__
    return await self.asgi_app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/a2wsgi/wsgi.py", line 165, in __call__
    return await responder(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/a2wsgi/wsgi.py", line 200, in __call__
    await self.loop.run_in_executor(
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/a2wsgi/wsgi.py", line 256, in wsgi
    iterable = self.app(environ, start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/apps/flask.py", line 68, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/decorators/main.py", line 134, in wrapper
    return decorated_function(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/decorators/response.py", line 171, in wrapper
    handler_response = function(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/decorators/parameter.py", line 87, in wrapper
    return function(**kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/venv-v3/lib/python3.12/site-packages/connexion/decorators/main.py", line 123, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/git/github/connexion_spec_first/examples/exception/hello.py", line 22, in post_greeting
    fall_on_face()
  File "/Users/me/git/github/connexion_spec_first/examples/exception/hello.py", line 17, in fall_on_face
    raise ValueError("I would prefer not to")
ValueError: I would prefer not to
INFO:     127.0.0.1:60200 - "POST /openapi/greeting/dave HTTP/1.1" 500 Internal Server Error
```

### Additional info:

Python 3.12
Connexion 3.1.0

**Comment by chrisinmtown** [comment]
By using the debugger I was able to figure out that the Python logging function `_log` calls `system.exc_info()` in this code block, about line 1657 in `logging/__init__.py`.:
```
        if exc_info:
            if isinstance(exc_info, BaseException):
                exc_info = (type(exc_info), exc_info, exc_info.__traceback__)
            elif not isinstance(exc_info, tuple):
                exc_info = sys.exc_info()
```
In v2, that function returns something useful:
```
> /usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/__init__.py(1661)_log()
-> exc_info = sys.exc_info()
(Pdb) sys.exc_info()
(<class 'ValueError'>, ValueError('I would prefer not to'), <traceback object at 0x10ebdb540>)
```
But in v3, that function returns None:
```
(Pdb) sys.exc_info()
(None, None, None)
```
I don't know enough about async features, I can only guess that maybe some aspect of that blocked the Python interpreter from finding the trace? I am still trying to find where connexion catches the exception, maybe that code has the extra bit of knowledge about the thread, stack frame or (?) that it can pass along so the basic logging feature will work again?

**Comment by chrisinmtown** [comment]
I finally found what I believe is the relevant try-except block in `starlette._exception_handler.py`, which looks up and calls my little exception handler about line 59:
```
            if is_async_callable(handler):
                response = await handler(conn, exc)
```
That motivated me to search the Starlette GitHub issues, and I found this:

https://github.com/encode/starlette/issues/2625

Is there some chance the problem actually originates in starlette, and has to be fixed there?

**Comment by chrisinmtown** [comment]
Here's a stupid idea: what if I define my exception handler as `async` so the Connexion function doesn't have to run my synchronous handler in a thread pool? Will the `sys.exc_info` call work then?  Not quite sure what all is required for my handler to be `async` tho.

**Comment by chrisinmtown** [comment]
I'm sure it will surprise none of the maintainers lol that this works just fine, the logger shows a full stack trace:
```
async def my_handle_exception(
        request: ConnexionRequest,
        ex: Exception) -> ConnexionResponse:
    logger.exception("Request caused exc: %s", ex)
    return problem(title='Exception', status=500, detail=str(ex))
```
Happy to have a solution, it raises many more questions:
* What can I do in my exception handler, and what can't I do, now that it's mysteriously `async` ?
* Would you look favorably on a PR to update this page: https://connexion.readthedocs.io/en/latest/exceptions.html

**Comment by RobbeSneyders** [comment]
Thanks for the report @chrisinmtown.

I would propose a different fix though. Seems like we're losing the stacktrace info since [we're running the sync function in a threadpool](https://github.com/spec-first/connexion/blob/1844a2fb3f1d09a37edfeab7a7200d52e97abbd9/connexion/middleware/exceptions.py#L39), which is probably not needed for error handlers.

So I would just call the error handler directly instead.

**Comment by chrisinmtown** [comment]
Thanks for the reply @RobbeSneyders.

Maybe you are telling me that the error handler is called from an async context already, so it doesn't really need to be declared  `async` and called via `await`? Just trying to understand.

Please let me know what you decide, I will adjust or drop PR https://github.com/spec-first/connexion/pull/2021

**Comment by RobbeSneyders** [comment]
The error handler is being called from an `async` context. If the error handler is `async`, it is called using `await`. If it is not `async`, it is executed in a threadpool:

https://github.com/spec-first/connexion/blob/1844a2fb3f1d09a37edfeab7a7200d52e97abbd9/connexion/middleware/exceptions.py#L36-L39

This is done to prevent the handler from blocking the event loop. The downside is that it loses the stack trace information.

Now I'm wondering if we really need to call exception handlers in a threadpool, since I assume they usually won't do a lot of io. We could just call the handler directly, which would preserve the stack trace for sync error handlers.

**Comment by RobbeSneyders** [comment]
Looking at Starlette and FastAPI, they seem to have the same issue.

It's probably safest to keep running the sync handlers in a threadpool, since people might be logging errors.

So I would indeed go for a docs update, but I would not blindly recommend `async` handlers, since this can have other complications if users are using blocking io. I would just add a warning of the stacktrace being unavailable in sync handlers.

**Comment by chrisinmtown** [comment]
I revised my PR, it no longer blindly recommends `async` handlers, just warns that the stack trace is only available in an `async` routine. Please review again.

**Comment by chrisinmtown** [comment]
Happy new year @RobbeSneyders I think I addressed all your comments in this revised PR, would you please review?

**Comment by chrisinmtown** [comment]
Finally getting back to updating this issue. @RobbeSneyders pointed out that I can supply argument `exc_info` in the `logger.exception` call, and that neatly solves the problem, a stack trace is then shown just fine.
