### ISSUE TITLE
Returning files via connexion.send_file or connexion.send_from_directory return an error

### ISSUE THREAD

**Issue by thedylman** [spec-first/connexion#401]
### Description
Using connexion.send_file or connexion.send_from_directory return an error. I think this is because they don't return an ResponseContainer object.

### Expected behaviour
File should be sent in response.

### Actual behaviour
File not sent in response, console shows call stack:
```
  Traceback (most recent call last):
  File "/home/test/download/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/test/download/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/test/download/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/test/download/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/test/download/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/test/download/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/test/download/venv/lib/python3.5/site-packages/connexion/decorators/decorator.py", line 118, in wrapper
    response_container = function(*args, **kwargs)
  File "/home/test/download/venv/lib/python3.5/site-packages/connexion/decorators/produces.py", line 59, in wrapper
    response = function(*args, **kwargs)
  File "/home/test/download/venv/lib/python3.5/site-packages/connexion/decorators/response.py", line 90, in wrapper
    response = function(*args, **kwargs)
  File "/home/test/download/venv/lib/python3.5/site-packages/connexion/decorators/decorator.py", line 99, in wrapper
    return self.get_response_container(operation_handler_result)
  File "/home/test/download/venv/lib/python3.5/site-packages/connexion/decorators/decorator.py", line 61, in get_response_container
    self.mimetype, response=operation_handler_result)
  File "/home/test/download/venv/lib/python3.5/site-packages/connexion/decorators/decorator.py", line 153, in __init__
    self.data = self._response.get_data()
  File "/home/test/download/venv/lib/python3.5/site-packages/werkzeug/wrappers.py", line 906, in get_data
    self._ensure_sequence()
  File "/home/test/download/venv/lib/python3.5/site-packages/werkzeug/wrappers.py", line 955, in _ensure_sequence
    raise RuntimeError('Attempted implicit sequence conversion '
RuntimeError: Attempted implicit sequence conversion but the response object is in direct passthrough mode.
```

### Steps to reproduce
```
# setup venv
python3 -m venv --clear venv
source venv/bin/activate
pip3 install --upgrade pip
pip3 install connexion

# manually update swagger_spec_validator until its fixed.
pip3 install --upgrade https://github.com/Yelp/swagger_spec_validator/archive/v2.0.3.zip#egg=swagger_spec_validator-2.0.3

# add swagger.yaml + app.py to current directory.

# create file to upload
mkdir uploads
dd if=/dev/urandom of=uploads/test.bin bs=1024 count=100

# start app.py
python app.py

# download file
curl http://localhost:8000/test -v -o test_rsp.bin
```

swagger.yaml
```
swagger: '2.0'

info:
  version: "0.1.0"
  title: Download Test

schemes:
 - http
consumes:
 - multipart/form-data
produces:
 - application/octet-stream

paths:
  /test:
    get:
      description: download file.
      operationId: "app.test_get"
      responses:
        200:
          description: OK
          schema:
            type: file
```

app.py
```
import connexion
from connexion.decorators.decorator import ResponseContainer

def test_get():
    resp = connexion.send_from_directory('uploads', 'test.bin',
         as_attachment=True, 
         mimetype='application/octet-stream',
         attachment_filename='test_rsp.bin'
    )
    return resp

def main():
    app = connexion.App(__name__, specification_dir='./swagger/')
    app.add_api('swagger.yaml', strict_validation=True, validate_responses=True)
    app.run(host='0.0.0.0', port=8000, threaded=True)

if __name__ == '__main__':
    main()

```

### Additional info:

Output of the commands:
- `python --version`== Python 3.5.2
- `pip show connexion | grep "^Version\:"` == Version: 1.1.4
- `pip list` ==
```appdirs (1.4.0)
click (6.7)
clickclick (1.2.1)
connexion (1.1.4)
Flask (0.12)
itsdangerous (0.24)
Jinja2 (2.9.5)
jsonschema (2.6.0)
MarkupSafe (0.23)
packaging (16.8)
pip (9.0.1)
pkg-resources (0.0.0)
pyparsing (2.1.10)
PyYAML (3.12)
requests (2.13.0)
setuptools (34.1.1)
six (1.10.0)
strict-rfc3339 (0.7)
swagger-spec-validator (2.0.3)
Werkzeug (0.11.15)
```

### Workaround
Wrapping it in a ResponseContainer seems to allow it to pass through Connexion but it disables direct passthrough mode set by send_from_directory().

```
def test_get():
    resp = connexion.send_from_directory('uploads', 'test.bin',
         as_attachment=True, 
         mimetype='application/octet-stream',
         attachment_filename='test_rsp.bin'
    )

    return ResponseContainer(
        mimetype=resp.mimetype,
        data=resp.response,
        status_code=200,
        headers=resp.headers
    )
```

**Comment by thedylman** [comment]
This is the next problem after fixing the swagger_spec_validator issue described in #324

**Comment by holdenweb** [comment]
Is there any known workaround for this issue?

**Comment by EmlynC** [comment]
Hello @thedylman, I think the error here is caused by `validate_responses=True` — this leads to the `RuntimeError` described. Essentially, `connexion` calls `response.get_data()` to deserialise the response and it throws an error because you can't coerce the stream into an object without calling the chunk methods.

**Comment by gitttt** [comment]
So what is the solution here? How can I send a binary file and have `validate_responses=True` ?

**Comment by alexpdr** [comment]
Bumping as I have same issue

**Comment by crbn60** [comment]
I have the same issue, using code that looks like this:

```python
flask.send_file(spreadsheet,
                         mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                         as_attachment=True,
                         attachment_filename=F"labels_{domain}.xlsx")
```

Where `spreadsheet` is a file-like object. Also, I'm using `flask.send_file`, since I didn't find a `connexion.send_file`.

**Comment by phasath** [comment]
I'm having the same issue. Is it not fixed yet?
