### ISSUE TITLE
Using application/x-www-formencoded for requests

### ISSUE THREAD

**Issue by binrush** [spec-first/connexion#443]
### Description
Hello. I'm trying to get `sqlalchemy` connexion example working with x-www-formencoded requests instead of json ones. For this, i've just added additional value to `consumes` parameter in `swagger.yaml`:
```
consumes:
  - application/json
  - application/x-www-formencoded
```

And issued PUT request:

```
curl -X PUT --header 'Content-Type: application/x-www-formencoded' --header 'Accept: application/problem+json' -d 'name=Mourzique%26animal_type=cat' 'http://localhost:8080/pets/mourzique'
```

### Expected behaviour
Service returned 200

### Actual behaviour
Error 500 returned:
```
[2017-05-02 21:56:53,001] ERROR in app: Exception on /pets/mourzique [PUT]
Traceback (most recent call last):
  File "/home/rush/src/con-api/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rush/src/con-api/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rush/src/con-api/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rush/src/con-api/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rush/src/con-api/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rush/src/con-api/venv/local/lib/python2.7/site-packages/connexion/decorators/decorator.py", line 118, in wrapper
    response_container = function(*args, **kwargs)
  File "/home/rush/src/con-api/venv/local/lib/python2.7/site-packages/connexion/decorators/validation.py", line 122, in wrapper
    response = function(*args, **kwargs)
  File "/home/rush/src/con-api/venv/local/lib/python2.7/site-packages/connexion/decorators/validation.py", line 294, in wrapper
    return function(*args, **kwargs)
  File "/home/rush/src/con-api/venv/local/lib/python2.7/site-packages/connexion/decorators/produces.py", line 100, in wrapper
    response = function(*args, **kwargs)
  File "/home/rush/src/con-api/venv/local/lib/python2.7/site-packages/connexion/decorators/decorator.py", line 98, in wrapper
    operation_handler_result = function(*args, **kwargs)
  File "/home/rush/src/con-api/venv/local/lib/python2.7/site-packages/connexion/decorators/parameter.py", line 161, in wrapper
    return function(*args, **kwargs)
  File "/home/rush/src/connexion/examples/sqlalchemy/app.py", line 27, in put_pet
    pet['id'] = pet_id
TypeError: 'str' object does not support item assignment
```

Is it possible to use `x-www-formencoded` requests with connexion?

**Comment by hjacobs** [comment]
Can you provider your `swagger.yaml`? IIRC it's not enough to change `consumes`, you also need to change the parameter type to `form`.

**Comment by binrush** [comment]
Thank your for reply.

Here is my `swagger.yaml`:
```yaml
swagger: '2.0'
info:
  title: Pet Shop Example API
  version: "0.1"
consumes:
  - application/json
  - application/x-www-formencoded
produces:
  - application/json
paths:
  /pets:
    get:
      tags: [Pets]
      operationId: app.get_pets
      summary: Get all pets
      parameters:
        - name: animal_type
          in: query
          type: string
          pattern: "^[a-zA-Z0-9]*$"
        - name: limit
          in: query
          type: integer
          minimum: 0
          default: 100
      responses:
        200:
          description: Return pets
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
  /pets/{pet_id}:
    get:
      tags: [Pets]
      operationId: app.get_pet
      summary: Get a single pet
      parameters:
        - $ref: '#/parameters/pet_id'
      responses:
        200:
          description: Return pet
          schema:
            $ref: '#/definitions/Pet'
        404:
          description: Pet does not exist
    put:
      tags: [Pets]
      operationId: app.put_pet
      summary: Create or update a pet
      parameters:
        - $ref: '#/parameters/pet_id'
        - name: pet
          in: body
          schema:
            $ref: '#/definitions/Pet'
      responses:
        200:
          description: Pet updated
        201:
          description: New pet created
    delete:
      tags: [Pets]
      operationId: app.delete_pet
      summary: Remove a pet
      parameters:
        - $ref: '#/parameters/pet_id'
      responses:
        204:
          description: Pet was deleted
        404:
          description: Pet does not exist


parameters:
  pet_id:
    name: pet_id
    description: Pet's Unique identifier
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-]+$"

definitions:
  Pet:
    type: form
    required:
      - name
      - animal_type
    properties:
      id:
        type: string
        description: Unique identifier
        example: "123"
        readOnly: true
      name:
        type: string
        description: Pet's name
        example: "Susie"
        minLength: 1
        maxLength: 100
      animal_type:
        type: string
        description: Kind of animal
        example: "cat"
        minLength: 1
      created:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true
```

Can you please suggest, where should I change parameter type to `form`?
