### ISSUE TITLE
Possible Connexion Swagger Parsing Issue

### ISSUE THREAD

**Issue by jcantu-usgs** [spec-first/connexion#557]
[swagger_server.zip](https://github.com/zalando/connexion/files/1599200/swagger_server.zip)
### Description
I have a swagger yaml doc that I generated python-flask code for on the editor.swagger.io site.  When I have no SQLAlchemy code in my models, it all starts up fine.  The minute I try to tie the model to a table I get an error.  Depending on whether I use 1.1.9 or 1.2, the error is different.

Version 1.1.9 yields this error:
```
  File "/Users/jcantu/Projects/files-api/api/venv/lib/python3.6/site-packages/connexion/resolver.py", line 39, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/Users/jcantu/Projects/files-api/api/venv/lib/python3.6/site-packages/connexion/resolver.py", line 68, in resolve_function_from_operation_id
    raise ResolverError(msg)
connexion.exceptions.ResolverError: <ResolverError: Cannot resolve operationId "swagger_server.controllers.file_service_controller.get_service"!>
```
Version 1.2 yields this error:
```
  File "/Users/jcantu/Projects/files-api/api/venv/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 437, in _setup_table
    **table_kw)
  File "/Users/jcantu/Projects/files-api/api/venv/lib/python3.6/site-packages/flask_sqlalchemy/model.py", line 89, in __table_cls__
    if key in cls.metadata.tables:
AttributeError: 'property' object has no attribute 'tables'


```

### Expected behaviour
My Connexion Flask app starts normally.

### Actual behaviour
As soon as connexion reads the swagger.yaml doc (on line 20 of __main__.py), we have a failure.

### Steps to reproduce
See the attached flask project (zipped)
[swagger_server.zip](https://github.com/zalando/connexion/files/1599202/swagger_server.zip)
Also, here's a docker image for the database:
[database.zip](https://github.com/zalando/connexion/files/1599207/database.zip)

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by hjacobs** [comment]
@jcantu-usgs please check your code, the problem seems not to be related with Swagger parsing as far as I can see.

**Comment by jcantu-usgs** [comment]
@hjacobs I think I'm getting closer if I could please have an explanation for what is meant by this exception?:

`connexion.exceptions.ResolverError: <ResolverError: 'property' object has no attribute 'tables'>`

Here's the full stacktrace:
`Failed to add operation for POST /files/file
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/connexion/apis/abstract.py", line 242, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "/usr/local/lib/python3.6/site-packages/connexion/apis/abstract.py", line 195, in add_operation
    pythonic_params=self.pythonic_params)
  File "/usr/local/lib/python3.6/site-packages/connexion/operation.py", line 215, in __init__
    resolution = resolver.resolve(self)
  File "/usr/local/lib/python3.6/site-packages/connexion/resolver.py", line 40, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/usr/local/lib/python3.6/site-packages/connexion/resolver.py", line 67, in resolve_function_from_operation_id
    raise ResolverError(str(e), sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: 'property' object has no attribute 'tables'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jcantu/Library/Application Support/IntelliJIdea2017.3/python/helpers/pydev/pydevd.py", line 1683, in <module>
    main()
  File "/Users/jcantu/Library/Application Support/IntelliJIdea2017.3/python/helpers/pydev/pydevd.py", line 1677, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/jcantu/Library/Application Support/IntelliJIdea2017.3/python/helpers/pydev/pydevd.py", line 1104, in run
    runpy._run_module_as_main(module_name, alter_argv=False)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jcantu/Projects/files-api/api/swagger_server/__main__.py", line 46, in <module>
    connexionApp = create_app()
  File "/Users/jcantu/Projects/files-api/api/swagger_server/__main__.py", line 31, in create_app
    connexionApp.add_api('swagger.yaml', arguments={'title': 'standard public schema'})
  File "/usr/local/lib/python3.6/site-packages/connexion/apps/flask_app.py", line 54, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/connexion/apps/abstract.py", line 159, in add_api
    options=api_options.as_dict())
  File "/usr/local/lib/python3.6/site-packages/connexion/apis/abstract.py", line 131, in __init__
    self.add_paths()
  File "/usr/local/lib/python3.6/site-packages/connexion/apis/abstract.py", line 249, in add_paths
    self._handle_add_operation_error(path, method, err.exc_info)
  File "/usr/local/lib/python3.6/site-packages/connexion/apis/abstract.py", line 263, in _handle_add_operation_error
    six.reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/connexion/resolver.py", line 62, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/usr/local/lib/python3.6/site-packages/connexion/utils.py", line 34, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jcantu/Projects/files-api/api/swagger_server/controllers/file_controller.py", line 3, in <module>
    from swagger_server.models.file import File
  File "/Users/jcantu/Projects/files-api/api/swagger_server/models/__init__.py", line 5, in <module>
    from .file import File
  File "/Users/jcantu/Projects/files-api/api/swagger_server/models/file.py", line 12, in <module>
    class File(db.Model, Model):
  File "/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/model.py", line 67, in __init__
    super(NameMetaMixin, cls).__init__(name, bases, d)
  File "/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/model.py", line 121, in __init__
    super(BindMetaMixin, cls).__init__(name, bases, d)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/declarative/api.py", line 64, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 131, in __init__
    self._setup_table()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 395, in _setup_table
    **table_kw)
  File "/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/model.py", line 89, in __table_cls__
    if key in cls.metadata.tables:
AttributeError: 'property' object has no attribute 'tables'`
