### ISSUE TITLE
Add basic example with both HTTP Basic Auth & RestyResolver

### ISSUE THREAD

**Issue by Ryan-Gordon** [spec-first/connexion#562]
### Description

I am trying to implement some basic auth on certain operations in a project using FlaskInjector and RestyResolver. 

When adding basic auth to an operation in the swagger spec it throws an error :

### Actual behaviour
Crashes the application and returns this traceback : 
```
Traceback (most recent call last):
  File "app.py", line 24, in <module>
    app.add_api('my_super_app.yaml', resolver=RestyResolver('api'))
  File "/Users/ryangordon/Documents/Final-Year-Project-API/my_venv_dir/lib/python3.6/site-packages/connexion/apps/flask_app.py", line 54, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/Users/ryangordon/Documents/Final-Year-Project-API/my_venv_dir/lib/python3.6/site-packages/connexion/apps/abstract.py", line 159, in add_api
    options=api_options.as_dict())
  File "/Users/ryangordon/Documents/Final-Year-Project-API/my_venv_dir/lib/python3.6/site-packages/connexion/apis/abstract.py", line 131, in __init__
    self.add_paths()
  File "/Users/ryangordon/Documents/Final-Year-Project-API/my_venv_dir/lib/python3.6/site-packages/connexion/apis/abstract.py", line 252, in add_paths
    self._handle_add_operation_error(path, method, sys.exc_info())
  File "/Users/ryangordon/Documents/Final-Year-Project-API/my_venv_dir/lib/python3.6/site-packages/connexion/apis/abstract.py", line 263, in _handle_add_operation_error
    six.reraise(*exc_info)
  File "/Users/ryangordon/Documents/Final-Year-Project-API/my_venv_dir/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/ryangordon/Documents/Final-Year-Project-API/my_venv_dir/lib/python3.6/site-packages/connexion/apis/abstract.py", line 242, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "/Users/ryangordon/Documents/Final-Year-Project-API/my_venv_dir/lib/python3.6/site-packages/connexion/apis/abstract.py", line 196, in add_operation
    self._add_operation_internal(method, path, operation)
  File "/Users/ryangordon/Documents/Final-Year-Project-API/my_venv_dir/lib/python3.6/site-packages/connexion/apis/flask_api.py", line 87, in _add_operation_internal
    function = operation.function
  File "/Users/ryangordon/Documents/Final-Year-Project-API/my_venv_dir/lib/python3.6/site-packages/connexion/operation.py", line 393, in function
    security_decorator = self.security_decorator
  File "/Users/ryangordon/Documents/Final-Year-Project-API/my_venv_dir/lib/python3.6/site-packages/connexion/operation.py", line 84, in security_decorator
    security_definition = self.security_definitions[scheme_name]
KeyError: 'basic'

```
### Steps to reproduce

Attempt to use both basic authentication and resty resolver in a python project.

### Additional info:

Output of the commands:

- `python --version` `Python 3.6.1 :: Anaconda 4.4.0 (x86_64)`
- `pip show connexion | grep "^Version\:"` 'Version: 1.3'

**Comment by zhuwei05** [comment]
Got the same problem. @Ryan-Gordon Did you have solve it?

**Comment by roytanmoy** [comment]
Is this resolved part of any other ticket?

**Comment by roytanmoy** [comment]
@Ryan-Gordon @zhuwei05  Anybody of you got it working?
