### ISSUE TITLE
Inaccurate error message for ResolverErrors

### ISSUE THREAD

**Issue by WouldYouKindly** [spec-first/connexion#590]
### Description
I misspelled the name of the module in swagger.yaml and got this traceback:

```
Failed to add operation for GET /api/block/forecast
Traceback (most recent call last):
  File "/Users/ptz/.virtualenvs/with_connexion/lib/python3.6/site-packages/connexion/apis/abstract.py", line 250, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "/Users/ptz/.virtualenvs/with_connexion/lib/python3.6/site-packages/connexion/apis/abstract.py", line 203, in add_operation
    pythonic_params=self.pythonic_params)
  File "/Users/ptz/.virtualenvs/with_connexion/lib/python3.6/site-packages/connexion/operation.py", line 223, in __init__
    resolution = resolver.resolve(self)
  File "/Users/ptz/.virtualenvs/with_connexion/lib/python3.6/site-packages/connexion/resolver.py", line 40, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/Users/ptz/.virtualenvs/with_connexion/lib/python3.6/site-packages/connexion/resolver.py", line 65, in resolve_function_from_operation_id
    raise ResolverError(msg, sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: Cannot resolve operationId "with_flas.block"! Import error was "No module named 'with_flas'">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ptz/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/181.4892.64/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Users/ptz/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/181.4892.64/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/ptz/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/181.4892.64/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/ptz/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/181.4892.64/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/ptz/stuff/with_connexion/with_flask.py", line 9, in <module>
    app.add_api('swagger.yml')
  File "/Users/ptz/.virtualenvs/with_connexion/lib/python3.6/site-packages/connexion/apps/flask_app.py", line 54, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/Users/ptz/.virtualenvs/with_connexion/lib/python3.6/site-packages/connexion/apps/abstract.py", line 159, in add_api
    options=api_options.as_dict())
  File "/Users/ptz/.virtualenvs/with_connexion/lib/python3.6/site-packages/connexion/apis/abstract.py", line 139, in __init__
    self.add_paths()
  File "/Users/ptz/.virtualenvs/with_connexion/lib/python3.6/site-packages/connexion/apis/abstract.py", line 257, in add_paths
    self._handle_add_operation_error(path, method, err.exc_info)
  File "/Users/ptz/.virtualenvs/with_connexion/lib/python3.6/site-packages/connexion/apis/abstract.py", line 271, in _handle_add_operation_error
    six.reraise(*exc_info)
  File "/Users/ptz/.virtualenvs/with_connexion/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/ptz/.virtualenvs/with_connexion/lib/python3.6/site-packages/connexion/resolver.py", line 62, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/Users/ptz/.virtualenvs/with_connexion/lib/python3.6/site-packages/connexion/utils.py", line 36, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'with_flas'
```

This happens due to passing `ResolverError.exc_info` to `AbstractAPI._handle_add_operation_error` at https://github.com/zalando/connexion/blob/master/connexion/apis/abstract.py#L257. IIUC `sys.exc_info()` should be passed so that `ResolverError` is reraised.

### Expected behaviour
It would be much nicer to have `ResolverError` message at the bottom and get rid of original `ImportError` altogether. The `ResolverError` message is very nice and helpful, it shouldn't be shaded be low-level `ImportError` (:

### Steps to reproduce
Just follow the docs and misspell the module name.

### Additional info:

Output of the commands:

- `python --version` 3.6.3
- `pip show connexion | grep "^Version\:"` 1.4.2

**Comment by WouldYouKindly** [comment]
Completely unrelated question, but I maybe it's better than a separate issue. 

What do you think about checking that handler function signature matches swagger spec? E.g. in spec I have only `user_id` parameter, but handler function accepts two parameters. In that case `connexion` might raise an error on startup, instead of failing at runtime.

If you think this would be useful, I might try to submit a PR.
