### ISSUE TITLE
InvalidSpecification error when trying to use Open Service Broker API specification file

### ISSUE THREAD

**Issue by carlburger** [spec-first/connexion#941]
### Description
I am trying to build a Open Service Broker API with connexion and first used for this the official specification file for Open API 2 (https://github.com/openservicebrokerapi/servicebroker/blob/master/swagger.yaml). This worked fine but as soon as I switched to the Open API 3.0 file (https://github.com/openservicebrokerapi/servicebroker/blob/master/openapi.yaml) I got the following error:

```
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    app.add_api('api_v3.yaml')
  File "C:\APPS\python\lib\site-packages\connexion\apps\flask_app.py", line 54, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "C:\APPS\python\lib\site-packages\connexion\apps\abstract.py", line 155, in add_api
    options=api_options.as_dict())
  File "C:\APPS\python\lib\site-packages\connexion\apis\abstract.py", line 73, in __init__
    self.specification = Specification.load(specification, arguments=arguments)
  File "C:\APPS\python\lib\site-packages\connexion\spec.py", line 151, in load
    return cls.from_file(spec, arguments=arguments)
  File "C:\APPS\python\lib\site-packages\connexion\spec.py", line 108, in from_file
    return cls.from_dict(spec)
  File "C:\APPS\python\lib\site-packages\connexion\spec.py", line 146, in from_dict
    return OpenAPISpecification(spec)
  File "C:\APPS\python\lib\site-packages\connexion\spec.py", line 39, in __init__
    self._validate_spec(raw_spec)
  File "C:\APPS\python\lib\site-packages\connexion\spec.py", line 232, in _validate_spec
    raise InvalidSpecification.create_from(e)
connexion.exceptions.InvalidSpecification: {'description': 'catalog response', 'content': {'application/json': {'schema': {'$ref': '#/components/schemas/Catalog', 'x-scope': ['']}}}} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^/']['properties']['get']['properties']['responses']['patternProperties']['^([0-9X]{3})$']:
    {'oneOf': [{'$ref': '#/definitions/response'},
               {'$ref': '#/definitions/reference'}]}

On instance['paths']['/v2/catalog']['get']['responses']['200']:
    {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/Catalog',
                                                 'x-scope': ['']}}},
     'description': 'catalog response'}
```

There were some minor issues with the specification file which I solved with help from https://editor.swagger.io/ but the error is still there.

I think the issue has to do with the included JSONSchema reference in the specification file:

`
    JSONSchema:
      $ref: 'http://json-schema.org/draft-04/schema'`

### Steps to reproduce

Create a simple connexion app and use the Open Service Broker API specification file as API specification.

### Additional info:

Output of the commands:

- `python --version`
Python 3.7.2rc1

- `pip show connexion | grep "^Version\:"`
Version: 2.2.0

app.py:

```
import connexion
from connexion.decorators.uri_parsing import OpenAPIURIParser

options = {'uri_parsing_class': OpenAPIURIParser}

app = connexion.App(__name__, specification_dir='OpenAPI/', options=options)
app.add_api('api_v3.yaml')


if __name__ == "__main__":
    app.run(port=8080, debug=True)
```

Full used specification file:

```
# This is the Open API interface for Open Service Broker API. Every attempt will
# be made to make the Open API version of OSB API accurately represent the
# written specification. If the spec and this document conflict, the spec is
# the authority.

openapi: "3.0.0"

info:
  title: Open Service Broker API
  description: The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Open Service Broker API
    url: https://www.openservicebrokerapi.org/
    email: open-service-broker-api@googlegroups.com
  version: master - might contain changes that are not yet released

servers:
  - url: http://localhost:8080
    description: Broker Endpoint
  - url: http://localhost:3000
    description: OSB Checker - MockOSB

paths:
  /v2/catalog:
    get:
      summary: get the catalog of services that the service broker offers
      tags:
        - Catalog
      operationId: modules.catalog.get
      parameters:
        - $ref: '#/components/parameters/APIVersion'
      responses:
        '200':
          description: catalog response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Catalog'

  /v2/service_instances/{instance_id}:
    put:
      summary: provision a service instance
      tags:
        - ServiceInstances
      operationId: modules.serviceInstance.provision
      parameters:
        - $ref: '#/components/parameters/APIVersion'
        - $ref: '#/components/parameters/OriginatingIdentity'
        - name: instance_id
          in: path
          description: instance id of instance to provision
          required: true
          schema:
            type: string
        - name: accepts_incomplete
          in: query
          description: asynchronous operations supported
          schema:
            type: boolean
      requestBody:
        description: parameters for the requested service instance provision
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceInstanceProvisionRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceProvision'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceProvision'
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceAsyncOperation'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: update a service instance
      tags:
        - ServiceInstances
      operationId: modules.serviceInstance.update
      parameters:
        - $ref: '#/components/parameters/APIVersion'
        - $ref: '#/components/parameters/OriginatingIdentity'
        - name: instance_id
          in: path
          description: instance id of instance to update
          required: true
          schema:
            type: string
        - name: accepts_incomplete
          in: query
          description: asynchronous operations supported
          schema:
            type: boolean
      requestBody:
        description: parameters for the requested service instance update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceInstanceUpdateRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceAsyncOperation'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: deprovision a service instance
      tags:
        - ServiceInstances
      operationId: modules.serviceInstance.deprovision
      parameters:
        - $ref: '#/components/parameters/APIVersion'
        - $ref: '#/components/parameters/OriginatingIdentity'
        - name: instance_id
          in: path
          description: id of instance being deleted
          required: true
          schema:
            type: string
        - name: service_id
          in: query
          description: id of the service associated with the instance being deleted
          required: true
          schema:
            type: string
        - name: plan_id
          in: query
          description: id of the plan associated with the instance being deleted
          required: true
          schema:
            type: string
        - name: accepts_incomplete
          in: query
          description: asynchronous deprovision supported
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperation'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Gone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: get a service instance
      tags:
        - ServiceInstances
      operationId: modules.serviceInstance.get
      parameters:
        - $ref: '#/components/parameters/APIVersion'
        - $ref: '#/components/parameters/OriginatingIdentity'
        - name: instance_id
          in: path
          description: instance id of instance to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceResource'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v2/service_instances/{instance_id}/last_operation:
    get:
      summary: get the last requested operation state for service instance
      tags:
        - ServiceInstances
      operationId: modules.serviceInstance.lastOperation.get
      parameters:
        - $ref: '#/components/parameters/APIVersion'
        - name: instance_id
          in: path
          description: instance id of instance to find last operation applied to it
          required: true
          schema:
            type: string
        - name: service_id
          in: query
          description: id of the service associated with the instance
          schema:
            type: string
        - name: plan_id
          in: query
          description: id of the plan associated with the instance
          schema:
            type: string
        - name: operation
          in: query
          description: a provided identifier for the operation
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LastOperationResource'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Gone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v2/service_instances/{instance_id}/service_bindings/{binding_id}/last_operation:
    get:
      summary: get the last requested operation state for service binding
      tags:
        - ServiceBindings
      operationId: modules.serviceBinding.lastOperation.get
      parameters:
        - $ref: '#/components/parameters/APIVersion'
        - name: instance_id
          in: path
          description: instance id of instance to find last operation applied to it
          required: true
          schema:
            type: string
        - name: binding_id
          in: path
          description: binding id of service binding to find last operation applied to it
          required: true
          schema:
            type: string
        - name: service_id
          in: query
          description: id of the service associated with the instance
          schema:
            type: string
        - name: plan_id
          in: query
          description: id of the plan associated with the instance
          schema:
            type: string
        - name: operation
          in: query
          description: a provided identifier for the operation
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LastOperationResource'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Gone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v2/service_instances/{instance_id}/service_bindings/{binding_id}:
    put:
      summary: generate a service binding
      tags:
        - ServiceBindings
      operationId: modules.serviceBinding.binding
      parameters:
        - $ref: '#/components/parameters/APIVersion'
        - $ref: '#/components/parameters/OriginatingIdentity'
        - name: instance_id
          in: path
          description: instance id of instance to create a binding on
          required: true
          schema:
            type: string
        - name: binding_id
          in: path
          description: binding id of binding to create
          required: true
          schema:
            type: string
        - name: accepts_incomplete
          in: query
          description: asynchronous operations supported
          schema:
            type: boolean
      requestBody:
        description: parameters for the requested service binding
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceBindingRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceBinding'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceBinding'
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperation'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: deprovision a service binding
      tags:
        - ServiceBindings
      operationId: modules.serviceBinding.unbinding
      parameters:
        - $ref: '#/components/parameters/APIVersion'
        - $ref: '#/components/parameters/OriginatingIdentity'
        - name: instance_id
          in: path
          description: id of the instance associated with the binding being deleted
          required: true
          schema:
            type: string
        - name: binding_id
          in: path
          description: id of the binding being deleted
          required: true
          schema:
            type: string
        - name: service_id
          in: query
          description: id of the service associated with the instance for which a binding is being deleted
          required: true
          schema:
            type: string
        - name: plan_id
          in: query
          description: id of the plan associated with the instance for which a binding is being deleted
          required: true
          schema:
            type: string
        - name: accepts_incomplete
          in: query
          description: asynchronous operations supported
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperation'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Gone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: get a service binding
      tags:
        - ServiceBindings
      operationId: modules.serviceBinding.get
      parameters:
        - $ref: '#/components/parameters/APIVersion'
        - $ref: '#/components/parameters/OriginatingIdentity'
        - name: instance_id
          in: path
          description: instance id of instance associated with the binding
          required: true
          schema:
            type: string
        - name: binding_id
          in: path
          description: binding id of binding to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceBindingResource'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  parameters:
    APIVersion:
      name: X-Broker-API-Version
      in: header
      description: version number of the Service Broker API that the Platform will use
      required: true
      schema:
        type: string
        default: '2.13'

    OriginatingIdentity:
      name: X-Broker-API-Originating-Identity
      in: header
      description: identity of the user that initiated the request from the Platform
      schema:
        type: string

    RetryAfter:
      name: Retry-After
      in: header
      description: Indicates when to retry the request
      required: false
      schema:
        type: string

  schemas:
    Catalog:
      type: object
      properties:
        services:
          type: array
          items:
            $ref: '#/components/schemas/Service'

    Service:
      type: object
      required:
        - name
        - id
        - description
        - bindable
        - plans
      properties:
        name:
          type: string
        id:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
        requires:
          type: array
          items:
            type: string
            enum:
              - syslog_drain
              - route_forwarding
              - volume_mount
        bindable:
          type: boolean
        metadata:
          $ref: '#/components/schemas/Metadata'
        dashboard_client:
          $ref: '#/components/schemas/DashboardClient'
        plan_updateable:
          type: boolean
        plans:
          type: array
          items:
            $ref: '#/components/schemas/Plan'

    DashboardClient:
      type: object
      properties:
        id:
            type: string
        secret:
            type: string
        redirect_uri:
            type: string

    Plan:
      type: object
      required:
        - id
        - name
        - description
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        metadata:
          $ref: '#/components/schemas/Metadata'
        free:
          type: boolean
          default: true
        bindable:
          type: boolean
        schemas:
          $ref: '#/components/schemas/Schemas'

    Schemas:
      type: object
      properties:
        service_instance:
          $ref: '#/components/schemas/ServiceInstanceSchema'
        service_binding:
          $ref: '#/components/schemas/ServiceBindingSchema'

    ServiceInstanceSchema:
      type: object
      properties:
        create:
          $ref: '#/components/schemas/SchemaParameters'
        update:
          $ref: '#/components/schemas/SchemaParameters'

    ServiceBindingSchema:
      type: object
      properties:
        create:
          $ref: '#/components/schemas/SchemaParameters'

    SchemaParameters:
      type: object
      properties:
        parameters:
          $ref: '#/components/schemas/JSONSchema'

    JSONSchema:
      $ref: 'http://json-schema.org/draft-04/schema'

    ServiceInstanceResource:
      type: object
      properties:
        service_id:
          type: string
        plan_id:
          type: string
        dashboard_url:
          type: string
        parameters:
          $ref: '#/components/schemas/Object'

    ServiceInstanceProvisionRequest:
      type: object
      required:
        - service_id
        - plan_id
        - organization_guid
        - space_guid
      properties:
        service_id:
          type: string
        plan_id:
          type: string
        context:
          $ref: '#/components/schemas/Context'
        organization_guid:
          type: string
          deprecated: true
        space_guid:
          type: string
          deprecated: true
        parameters:
          $ref: '#/components/schemas/Object'

    ServiceInstanceProvision:
      type: object
      properties:
        dashboard_url:
          type: string

    ServiceInstanceAsyncOperation:
      type: object
      properties:
        dashboard_url:
          type: string
        operation:
          type: string # could be a link object to last operation

    ServiceInstanceUpdateRequest:
      type: object
      required:
        - service_id
      properties:
        context:
          $ref: '#/components/schemas/Context'
        service_id:
          type: string
        plan_id:
          type: string
        parameters:
          $ref: '#/components/schemas/Object'
        previous_values:
          $ref: '#/components/schemas/ServiceInstancePreviousValues'

    ServiceInstancePreviousValues:
      type: object
      properties:
        service_id:
          type: string
          deprecated: true
        plan_id:
          type: string
        organization_id:
          type: string
          deprecated: true
        space_id:
          type: string
          deprecated: true

    AsyncOperation:
      type: object
      properties:
        operation:
          type: string

    LastOperationResource:
      type: object
      required:
        - state
      properties:
        state:
          type: string
          enum:
            - in progress
            - succeeded
            - failed
        description:
          type: string

    ServiceBindingResource:
      type: object
      properties:
        credentials:
          $ref: '#/components/schemas/Object'
        syslog_drain_url:
          type: string
        route_service_url:
          type: string
        volume_mounts:
          type: array
          items:
            $ref: '#/components/schemas/ServiceBindingVolumeMount'
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/ServiceBindingEndpoint'
        parameters:
          $ref: '#/components/schemas/Object'

    ServiceBindingRequest:
      type: object
      required:
        - service_id
        - plan_id
      properties:
        context:
          $ref: '#/components/schemas/Context'
        service_id:
          type: string
        plan_id:
          type: string
        app_guid:
          type: string
          deprecated: true
        bind_resource:
          $ref: '#/components/schemas/ServiceBindingResouceObject'
        parameters:
          $ref: '#/components/schemas/Object'

    ServiceBindingResouceObject:
      type: object
      properties:
        app_guid:
          type: string
        route:
          type: string

    ServiceBinding:
      type: object
      properties:
        credentials:
          $ref: '#/components/schemas/Object'
        syslog_drain_url:
          type: string
        route_service_url:
          type: string
        volume_mounts:
          type: array
          items:
            $ref: '#/components/schemas/ServiceBindingVolumeMount'
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/ServiceBindingEndpoint'

    ServiceBindingEndpoint:
      type: object
      required:
      - host
      - ports
      properties:
        host:
          type: string
        ports:
          type: array
          items:
            type: string
        protocol:
          type: string
          enum:
          - 'tcp'
          - 'udp'
          - 'all'
          default: 'tcp'

    ServiceBindingVolumeMount:
      type: object
      required:
        - driver
        - container_dir
        - mode
        - device_type
        - device
      properties:
        driver:
          type: string
        container_dir:
          type: string
        mode:
          type: string
          enum:
            - r
            - rw
        device_type:
          type: string
          enum:
            - shared
        device:
          $ref: '#/components/schemas/ServiceBindingVolumeMountDevice'

    ServiceBindingVolumeMountDevice:
      type: object
      required:
        - volume_id
      properties:
        volume_id:
          type: string
        mount_config:
          $ref: '#/components/schemas/Object'

    Context:
      description: "See [Context Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) for more details."
      type: object

    Metadata:
      description: "See [Service Metadata Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata) for more details."
      type: object

    Object:
      type: object

    Error:
      description: "See [Service Broker Errors](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-broker-errors) for more details."
      type: object
      properties:
        error:
          type: string
        description:
          type: string

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      x-basicInfoFunc: modules.authentication.get

security:
  - basicAuth: []

externalDocs:
  description: The offical Open Service Broker API specification
  url: https://github.com/openservicebrokerapi/servicebroker/
```

**Comment by jeeftor** [comment]
Ever make progress on this one?
